services:
  app:
    image: todo-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=//localhost:3001
      - CHOKIDAR_USEPOLLING=true #fixes docker file changes not being updated on webbrowser
    container_name: todo-frontend-dev # This will name the container hello-front-dev